name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Get source code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: Run unit tests
      - name: Run tests
        run: |
          python -m pytest
